name: Build and Deploy

permissions:
  contents: write

on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Ruby ✨
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install and Build Webpage 🔧
        run: |
          bundle exec nanoc compile
          bundle exec nanoc check internal_links mixed_content stale

      - name: Install and Build Slides 🔧
        run: |
          cd slides
          npm install
          npm run bundle
          mkdir -p ../output/slides
          cp -r bundled/* ../output/slides/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
          CLEAN: true
